🎯 Objetivos
Realizar un Análisis Exploratorio de Datos (EDA).

Determinar las etiquetas de entrenamiento (Training Labels).

Instala las siguientes librerías necesarias para el análisis.

In [ ]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

📚 Importar Librerías y Definir Funciones Auxiliares

📌 Traducción:
Importar librerías y definir funciones auxiliares

In [ ]:
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np

📊 Análisis de Datos

📌 Cargar el conjunto de datos de SpaceX desde la sección anterior.

In [ ]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

🔍 Identificar y calcular el porcentaje de valores faltantes por atributo

📌Identifica y calcula el porcentaje de valores faltantes en cada atributo (columna)

In [ ]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

Identificar qué columnas son numéricas y cuáles categóricas
Identifica qué columnas del conjunto de datos son numéricas y cuáles son categóricas

In [ ]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

# **TAREA 1: Calcular la cantidad de lanzamientos por sitio**
💬 Instrucción original: **texto en negrita**

📌 Calcula el número de lanzamientos en cada sitio de lanzamiento

📍 El nombre del sitio está en la columna LaunchSite.

In [ ]:
import pandas as pd

# Cargar el dataset desde el archivo subido
spacex_df = pd.read_csv('dataset_part_1.csv')

# Ver las primeras filas para confirmar que se cargó bien
spacex_df.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6123.547647,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

In [ ]:
# Contar la cantidad de lanzamientos por sitio
spacex_df['LaunchSite'].value_counts()

LaunchSite
CCSFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

🚀 Cada lanzamiento tiene como objetivo una órbita específica
Cada lanzamiento está destinado a una órbita específica, y aquí algunos tipos de órbitas comunes:

Aquí te dejo una lista explicada de los tipos de órbitas que probablemente veas en el dataset (Orbit):

Tipo de Órbita	Significado
-LEO	Low Earth Orbit: Órbita baja terrestre (hasta 2.000 km). Usada para satélites de observación, comunicación, y la EEI.
-GTO	Geostationary Transfer Orbit: Órbita de transferencia hacia una órbita geoestacionaria.
-GEO	Geostationary Orbit: Órbita geoestacionaria. Satélites permanecen sobre el mismo punto del ecuador.
-PO	Polar Orbit: Satélite cruza por los polos de la Tierra, usado para monitoreo global.
-ISS	International Space Station Orbit: Órbita específica de la EEI.
-HEO	Highly Elliptical Orbit: Órbita muy elíptica, utilizada para ciertas misiones científicas.
-MEO	Medium Earth Orbit: Usada por sistemas de navegación como GPS.
-SO	Sun-Synchronous Orbit: Mantiene la misma posición relativa al Sol, ideal para observación terrestre.
![image.png]()

# **TAREA 2: Calcular la cantidad y ocurrencia de cada órbita**

Utiliza el método .value_counts() para determinar la cantidad y la frecuencia de aparición de cada tipo de órbita en la columna Orbit.

In [ ]:
# Apply value_counts on Orbit column
spacex_df['Orbit'].value_counts()

Orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

# **TAREA 3: Calcular la cantidad y ocurrencia de los resultados de misión (Outcome)**
Usa el método .value_counts() en la columna Outcome para calcular cuántas veces aparece cada resultado de aterrizaje. Luego, asigna ese resultado a la variable landing_outcomes.

In [ ]:
# landing_outcomes = values on Outcome column
landing_outcomes = spacex_df['Outcome'].value_counts()
landing_outcomes

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

True Ocean significa que el resultado de la misión fue un aterrizaje exitoso en una zona específica del océano.

False Ocean indica que el aterrizaje en una zona específica del océano fue fallido.

True RTLS significa que la misión aterrizó exitosamente en una plataforma terrestre (RTLS = Return To Launch Site).

False RTLS indica que no se logró el aterrizaje en la plataforma terrestre.

True ASDS significa que la misión aterrizó exitosamente en una nave no tripulada en el océano (Autonomous Spaceport Drone Ship).

False ASDS indica que falló el aterrizaje en la nave no tripulada.

None ASDS y None None representan un fallo total en el aterrizaje, es decir, no se logró ningún tipo de recuperación del propulsor.

In [ ]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS


Creamos un conjunto de resultados donde la segunda etapa no aterrizó exitosamente.

In [ ]:
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

TAREA 4: Crear una etiqueta de resultado de aterrizaje desde la columna Outcome
Usando la columna Outcome, crea una lista donde el elemento sea 0 si la fila correspondiente está dentro del conjunto bad_outcomes; de lo contrario, que sea 1. Luego, asigna esa lista a la variable landing_class.

In [ ]:
## Add landing_class as a new column
spacex_df['Class'] = landing_class

# Verificar que se haya agregado correctamente
spacex_df[['Outcome', 'Class']].head()

       Outcome  Class
0    None None      0
1    None None      0
2    None None      0
3  False Ocean      0
4    None None      0

Esta variable representará la variable de clasificación que indica el resultado de cada lanzamiento.
Si el valor es cero (0), significa que la primera etapa no aterrizó con éxito;
Si el valor es uno (1), significa que la primera etapa aterrizó exitosamente.

In [ ]:
df['Class']=landing_class
df[['Class']].head(8)

   Class
0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      1

In [ ]:
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0

Podemos usar la siguiente línea de código para determinar la tasa de éxito:

In [ ]:
df["Class"].mean()

np.float64(0.6666666666666666)

Ahora podemos exportar el archivo a formato CSV para usarlo en la siguiente sección. Sin embargo, para que las respuestas sean consistentes, en el próximo laboratorio se proporcionarán los datos dentro de un rango de fechas preseleccionado.

In [ ]:
df.to_csv("dataset_part_2.csv", index=False)

In [ ]:
spacex_df['LaunchSite'].value_counts()

LaunchSite
CCSFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

In [ ]:
success_rate = spacex_df['Class'].mean()
print(f"Tasa de éxito: {success_rate:.2%}")

Tasa de éxito: 66.67%

In [ ]:
spacex_df['Orbit'].value_counts()

Orbit
GTO      27
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

In [ ]:
spacex_df['Outcome'].value_counts()

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64